name: Run Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    # Step to clean the project
    - name: Clean the project
      run: mvn clean

    - name: Install dependencies
      run: mvn install

    # Step to determine changed files in the PR
    - name: Get changed files
      id: get-changed-files
      run: |
        git fetch origin main
        changed_files=$(git diff --name-only HEAD $(git merge-base HEAD origin/main))
        echo "Changed files: $changed_files"
        echo "::set-output name=files::$changed_files"

    # Step to filter feature files from changed files
    - name: Filter feature files
      id: filter-feature-files
      run: |
        changed_files="${{ steps.get-changed-files.outputs.files }}"
        echo "Changed files: $changed_files"
        feature_files=$(echo "$changed_files" | grep -E '\.feature$')
        echo "Feature files: $feature_files"
        echo "::set-output name=features::$feature_files"

    # Step to run Cucumber Tests with filtered features
    - name: Run Cucumber Tests
      run: |
        feature_files="${{ steps.filter-feature-files.outputs.features }}"
        echo "Feature files to be tested: $feature_files"
        if [ -z "$feature_files" ]; then
          echo "No feature files changed. Skipping Cucumber tests."
        else
          mvn test -Dcucumber.options="$feature_files --plugin com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"
        fi

    # Debug step: List files in the target directory
    - name: List target directory files
      run: ls -R target

    # Upload Extent Reports
    - name: Upload Extent Reports
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: extent-reports
        path: target/extent-reports/*
