name: Run Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Clean and install dependencies
      run: |
        mvn clean
        mvn install -DskipTests

    - name: Run Cucumber Tests
      run: mvn test -Dcucumber.options="src/test/resources/features --plugin pretty --plugin html:target/cucumber-reports/cucumber-reports.html --glue Stepdefinition"

    # Debug step: List files in the target directory
    - name: List target directory files
      run: ls -R target

    # Upload Surefire reports
    - name: Upload Surefire Reports
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: surefire-reports
        path: target/surefire-reports/*

    # Upload Cucumber reports
    - name: Upload Cucumber Reports
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-reports
        path: target/cucumber-reports/*

    # Generate and Upload Allure Reports
    - name: Generate Allure Report
      if: success()
      run: mvn allure:report

    - name: Upload Allure Report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/site/allure-maven-plugin/*
