name: Run Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      Tag:
        description: 'Tag to run'
        required: true
        type: choice
        options:
          - smoketest
          - regression

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Make script executable
      run: chmod +x ./.github/workflows/determine-tags.sh

    - name: Determine Tags from Feature Files
      id: determine_tags
      run: |
        echo "Event: ${{ github.event_name }}"  # For debugging
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "Manual run with tag input: ${{ github.event.inputs.Tag }}"
          echo "TAG_STRING=${{ github.event.inputs.Tag }}" >> $GITHUB_ENV
        else
          TAG=$(./.github/workflows/determine-tags.sh)
          echo "TAG_STRING=${TAG}" >> $GITHUB_ENV
          echo "Tag string for Maven: ${TAG}"
        fi

    - name: Clean the project
      run: mvn clean

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run Cucumber Tests
      run: |
        echo "Running with TAG_STRING: $TAG_STRING"  # Debugging
        if [ -n "$TAG_STRING" ]; then
          mvn test -Dcucumber.filter.tags="$TAG_STRING" -Dcucumber.plugin="com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"
        else
          mvn test -Dcucumber.plugin="com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"
        fi

    - name: List target directory files
      run: ls -R target

    - name: Upload Extent Reports
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: extent-reports
        path: target/extent-reports/*
